version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - mvn clean install
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name lampda-CICD --zip-file fileb:///root/.m2/repository/org/springframework/boot/spring-boot-starter-parent/2.7.11/spring-boot-starter-parent-2.7.11.jar
      - echo "DONE!!"
artifacts:
  files:
    - target/spring-boot-starter-parent-2.7.11.jar
  discard-paths: yes